'use strict';
const { guildId, optId, optList } = require('./_helpers');

const memberChannelsCategoryId =
  optId('MEMBER_CHANNELS_CATEGORY_ID') || guildId('BAIRRISTA_TOPICOS_CATEGORY_ID', 'categories') || '1495206698791600159';
const memberArchiveCategoryId = optId('MEMBER_ARCHIVE_CATEGORY_ID') || optId('BAIRRISTA_ARQUIVO_CATEGORY_ID');

module.exports = {
  MEMBER_CHANNELS_CATEGORY_ID: memberChannelsCategoryId,
  BAIRRISTA_TOPICOS_CATEGORY_ID: memberChannelsCategoryId,
  MEMBER_CHANNELS_OVERFLOW_CATEGORY_IDS: optList('MEMBER_CHANNELS_OVERFLOW_CATEGORY_IDS'),
  BAIRRISTA_TOPICOS_OVERFLOW_CATEGORY_IDS: optList('BAIRRISTA_TOPICOS_OVERFLOW_CATEGORY_IDS'),
  MEMBER_ARCHIVE_CATEGORY_ID: memberArchiveCategoryId,
  BAIRRISTA_ARQUIVO_CATEGORY_ID: memberArchiveCategoryId,
  TAG_REQUEST_CHANNEL_ID: guildId('TAG_REQUEST_CHANNEL_ID', 'channels'),
  PANEL_ENTRADA_CHANNEL_ID: guildId('PANEL_ENTRADA_CHANNEL_ID', 'channels'),
  AUDIT_LOG_CHANNEL_ID: optId('AUDIT_LOG_CHANNEL_ID'),
  STRUCTURE_SYNC_LOG_CHANNEL_ID: optId('STRUCTURE_SYNC_LOG_CHANNEL_ID'),
};
