'use strict';
const { guildId, optId } = require('./_helpers');

module.exports = {
  MANDA_CHUVA_ROLE_ID: guildId('MANDA_CHUVA_ROLE_ID'),
  KINGPIN_ROLE_ID: guildId('KINGPIN_ROLE_ID'),
  OG_ROLE_ID: guildId('OG_ROLE_ID'),
  REAL_GANGSTER_ROLE_ID: guildId('REAL_GANGSTER_ROLE_ID'),
  PATRAO_DI_ZONA_ROLE_ID: guildId('PATRAO_DI_ZONA_ROLE_ID'),
  YOUNG_BLOOD_ROLE_ID: guildId('YOUNG_BLOOD_ROLE_ID'),
  TROPINHA_DI_ZONA_ROLE_ID: optId('TROPINHA_DI_ZONA_ROLE_ID', '1490397688800477215'),
  O_GUNAO_ROLE_ID: guildId('O_GUNAO_ROLE_ID'),
  GANGSTER_FODIDO_ROLE_ID: guildId('GANGSTER_FODIDO_ROLE_ID'),
  BAIRRISTAS_BASE_ROLE_ID: guildId('BAIRRISTAS_BASE_ROLE_ID'),
  PENDENTE_ROLE_ID: optId('PENDENTE_ROLE_ID'),
  BOT_ROLE_ID: optId('BOT_ROLE_ID'),

  // Aliases antigos opcionais preservados para compatibilidade com dados/config existentes.
  TROPINHAS_DO_GUETTO_ROLE_ID: optId('TROPINHAS_DO_GUETTO_ROLE_ID'),
  PATRULHA_PATA_ROLE_ID: optId('PATRULHA_PATA_ROLE_ID'),
  REDWOOD_ROLE_ID: optId('REDWOOD_ROLE_ID'),
  BAIRRISTAS_ROLE_ID: optId('BAIRRISTAS_ROLE_ID'),
};
