'use strict';

module.exports = {
  memberRepo: require('./member'),
  inventoryRepo: require('./inventory'),
  saidaRepo: require('./saida'),
  killRepo: require('./kill'),
  spotStatsRepo: require('./spotStats'),
  memberSaidaStatsRepo: require('./memberSaidaStats'),
  memberAnalyticsRepo: require('./memberAnalytics'),
  rankingRepo: require('./ranking'),
  monthlyRankingRepo: require('./monthlyRanking'),
  jobRepo: require('./job'),
  radioRepo: require('./radio'),
  stickyRepo: require('./sticky'),
  bairristaStatsRepo: require('./bairristaStats'),
  deliveryRequestRepo: require('./deliveryRequest'),
  ordersRepo: require('./orders'),
  craftRecipeRepo: require('./craftRecipe'),
  prizeRepo: require('./prizeRepo'),
  itemAdminRepo: require('./itemAdmin'),
  memberLifecycleRepo: require('./memberLifecycle'),
  incidentRepo: require('./incident'),
  absenceRepo: require('./absence'),
  inventoryBalanceRepo: require('./inventoryBalance'),
  MessageRegistryRepo: require('./messageRegistry'),
};
