'use strict';

module.exports = {
  memberRepo: require('./member'),
  inventoryRepo: require('./inventory'),
  saidaRepo: require('./saida'),
  killRepo: require('./kill'),
  spotStatsRepo: require('./spotStats'),
  memberSaidaStatsRepo: require('./memberSaidaStats'),
  memberAnalyticsRepo: require('./memberAnalytics'),
  rankingRepo: require('./ranking'),
  monthlyRankingRepo: require('./monthlyRanking'),
  auditRepo: require('./audit'),
  jobRepo: require('./job'),
  availabilityRepo: require('./availability'),
  radioRepo: require('./radio'),
  stickyRepo: require('./sticky'),
  bairristaStatsRepo: require('./bairristaStats'),
  deliveryRequestRepo: require('./deliveryRequest'),
  ordersRepo: require('./orders'),
  craftRecipeRepo: require('./craftRecipe'),
  prizeRepo: require('./prizeRepo'),
  itemAdminRepo: require('./itemAdmin'),
  memberLifecycleRepo: require('./memberLifecycle'),
  dataQualityRepo: require('./dataQuality'),
  maintenanceRepo: require('./maintenance'),
  incidentRepo: require('./incident'),
  taskRepo: require('./task'),
  reputationRepo: require('./reputation'),
  absenceRepo: require('./absence'),
};
